### ISSUE TITLE
Several consecutive errors , i need help bro. 

### ISSUE THREAD

**Issue by NderKev** [tommyz7/erc1404-security-token#2]
Your Erc1404 has changes that changes from time time to tme and also if i try to chhose my mnemonic doesn't work . Is you template open source or we have to pay?

![Screenshot from 2019-09-05 04-40-30](https://user-images.githubusercontent.com/11832441/64306430-669daa00-cf9b-11e9-9eb2-4dc7c18baf67.png)
![Screenshot from 2019-09-04 12-49-14](https://user-images.githubusercontent.com/11832441/64306431-669daa00-cf9b-11e9-897d-38d592d80ccc.png)

**Comment by NderKev** [comment]
![Screenshot from 2019-09-05 04-16-37](https://user-images.githubusercontent.com/11832441/64306561-e166c500-cf9b-11e9-851d-0fa712c27f41.png)

**Comment by tommyz7** [comment]
This project is not actively maintained. Feel free to use it as you wish.

**Comment by NderKev** [comment]
any ideas?

**Comment by NderKev** [comment]
i have been using this template , kindly help me out bro. if you need some $ just ask

**Comment by tommyz7** [comment]
I'm sorry, I'm so swamped with work right now I am not able to give support at the moment.
